### ISSUE TITLE
Showing agent output JSON

### ISSUE THREAD

**Issue by swapneils** [Altaflux/agent-mimir#4]
Nice job on this so far, seems to be working well!

Your image demo in the README shows the JSON data returned by the agent, but on my own computer mimir is only showing the results in the command line. How can we see the input and output of the agent(s) as well, in order to better judge the model and our own prompts?

**Comment by Altaflux** [comment]
Hi @swapneils , thanks for showing interest in the project!

You can enable extra logging with the following flags for the `.env` file:
```
# Log tool response
MIMIR_LOG_TOOL_RESPONSE=true

# Log AI response
MIMIR_LOG_AI_RESPONSE=true
```
